version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-ollama
      - ENABLE_MODULES=text2vec-ollama
      - CLUSTER_HOSTNAME=node1
      - OLLAMA_BASE_URL=http://ollama:11434
      - TEXT2VEC_OLLAMA_MODEL=nomic-embed-text
    depends_on:
      - ollama
    networks:
      - weaviate-net

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - weaviate-net
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: >
      /bin/sh -c "
      ollama serve & 
      sleep 5 &&
      ollama pull nomic-embed-text &&
      wait
      "

volumes:
  ollama-data:

networks:
  weaviate-net:
    driver: bridge
