version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "${WEAVIATE_PORT:-8080}:${WEAVIATE_PORT:-8080}"
      - "${WEAVIATE_GRPC_PORT:-50051}:${WEAVIATE_GRPC_PORT:-50051}"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=${WEAVIATE_ANONYMOUS_ACCESS}
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-ollama
      - ENABLE_MODULES=text2vec-ollama
      - CLUSTER_HOSTNAME=node1
      - TEXT2VEC_OLLAMA_MODEL=${OLLAMA_TEXT2VEC_MODEL}
      - OLLAMA_HOST=${OLLAMA_BASE_URL}
    depends_on:
      - ollama
    networks:
      - weaviate-net

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - weaviate-net
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: >
      /bin/sh -c "
      ollama serve & 
      sleep 5 &&
      ollama pull ${OLLAMA_TEXT2VEC_MODEL} &&
      ollama pull ${OLLAMA_MODEL} &&
      wait
      "

volumes:
  ollama-data:

networks:
  weaviate-net:
    driver: bridge
